### ISSUE TITLE
upload to Package Control

### ISSUE THREAD

**Issue by oakmac** [oakmac/sublime-pretty-edn#1]
https://packagecontrol.io/docs/submitting_a_package

**Comment by oakmac** [comment]
https://github.com/wbond/package_control_channel/pull/8697

**Comment by oakmac** [comment]
[PR-8697](https://github.com/wbond/package_control_channel/pull/8697) was merged. Pretty EDN is now available via Package Control 🎉

**Comment by lostineverland** [comment]
FYI I had to install this manually as the Package Control version did not work on my M1 Mac. The issue was that the scripts were not installed with exec privillige.

**Comment by oakmac** [comment]
> FYI I had to install this manually as the Package Control version did not work on my M1 Mac. The issue was that the scripts were not installed with exec privillige.

Thank for reporting this @lostineverland 👍 

I am not sure if there can be a fix for this. The scripts have the executable bit set on them (ie: `chmod +x scripts/*.clj`) in the repo. This might be a limitation of Package Control or Sublime Text?
